### ISSUE TITLE
how to get position if dragtarget is list

### ISSUE THREAD

**Issue by mehtahardikr** [monkeyswarm/DragTargetDetailsExample#1]
if Dragtarget is listview then when drop the item how can we put that item on that index on which that item dragged.

for example. if dragitem 5 is  dragged to list(DragTarget)'s item at 1st index then this item 5 will be at index 1 as its dropped on it.

**Comment by monkeyswarm** [comment]
Your list should have a DragTarget on every list item (i.e. on every card). Then each DragTarget would have its own callback logic to inject its list index into the callback.

**Comment by mehtahardikr** [comment]
@monkeyswarm  : one question, weather need  to make whole list as Dragtarget or listitem or both ?
